[source]
type = "N2N"
address = "localhost:3000"

[enrich]
type = "Sled"
db_path = "/home/pioneer/scrolls/sled_db"

[[reducers]]
type = "UtxoByAddress"
key_prefix = "sundae.order"
# Order Contract address
filter = ["addr1wxaptpmxcxawvr3pzlhgnpmzz3ql43n2tc8mn3av5kx0yzs09tqh8"]

[[reducers]]
type = "LiquidityByTokenPair"
key_prefix = "pool"
member_prefix = "sun"
# Liquidity Pool Policy NFT
filter_policy_ids_hex = [
  "0029cb7c88c7567b63d1a512c0ed626aa169688ec980730c0473b913"
]
# Pool Contract address
pool_contract_address = "addr1w9qzpelu9hn45pefc0xr4ac4kdxeswq7pndul2vuj59u8tqaxdznu"

[[reducers]]
type = "UtxoByAddress"
key_prefix = "minswap.order"
# Order Contract address
filter = ["addr1wxn9efv2f6w82hagxqtn62ju4m293tqvw0uhmdl64ch8uwc0h43gt"]

[[reducers]]
type = "LiquidityByTokenPair"
key_prefix = "pool"
member_prefix = "min"
# Pool Factory NFT policy & Liquidity Pool Policy NFT
filter_policy_ids_hex = [
  "13aa2accf2e1561723aa26871e071fdf32c867cff7e7d50ad470d62f",
  "0be55d262b29f564998ff81efe21bdc0022621c12f15af08d0f2ddb1"
]
# Pool Contract address
pool_contract_address = "addr1z8snz7c4974vzdpxu65ruphl3zjdvtxw8strf2c2tmqnxz2j2c79gy9l76sdg0xwhd7r0c0kna0tycz4y5s6mlenh8pq0xmsha"

[policy]
missing_data = "Skip"

[storage]
type = "Redis"
connection_params = "redis://127.0.0.1:6379"

[intersect]
type = "Origin"

[chain]
type = "Mainnet"
