version: "3.7"

services:
  scrolls:
    image: ghcr.io/pczeglik-iohk/scrolls-testdrive:testdrive
    command: ["daemon"]
    environment:
      - RUST_LOG=info
    volumes:
      - ./daemon.toml:/etc/scrolls/daemon.toml
    links:
      - redis
  redis:
    image: arm64v8/redis
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
